#!/bin/bash
#set -x 
KHQUITCON=0
KHSSH=khssh
NAME=khxcon

GEOM=120x30
function help()
{
    echo -e "\`$NAME' launches an xterm console\n"		\
	    "Usage: $NAME con\n"				\
	    " -t <tty setting>  tty settings\n"
}

optcount=0;
while getopts "t:h" OPT
do
  case $OPT in
    ("t") SETTY="stty $OPTARG;"; (( optcount+=2 ));;
    ("h") help; exit -1;;
  esac
done

shift $optcount;
con="$1"

if [ -z $con ]; then
    help; exit -1;
fi

#exec xterm -geometry $GEOM -fg orange -bg black -e bash -c "$SETTY echo starting console: $con connection;$KHSSH $con; echo Console connection terminated; if (( $KHQUITCON == 1)); then echo  Quitting in 20 seconds; sleep 20; exit -1; fi; echo Press \<ctl-c\> to close window; read"

screen -d -m -S l4 bash -c "$SETTY echo starting console: $con connection;$KHSSH $con; echo Console connection terminated; if (( $KHQUITCON == 1)); then echo  Quitting in 20 seconds; sleep 20; exit -1; fi; echo Press \<ctl-c\> to close window; read"
